src/FlaskRTBCTF/ctf/routes.py
''' views / routes '''

from flask import Blueprint, render_template, flash, request
from flask_login import current_user, login_required
from FlaskRTBCTF import db, bcrypt
from FlaskRTBCTF.config import organization, box, userHash, rootHash, userScore, rootScore, LOGGING
from FlaskRTBCTF.models import User, Score
if LOGGING:
    from FlaskRTBCTF.models import Logs
from FlaskRTBCTF.ctf.forms import UserHashForm, RootHashForm
from datetime import datetime

ctf = Blueprint('ctf', __name__)


''' Scoreboard '''

@ctf.route("/scoreboard")
@login_required
def scoreboard():
    scores = Score.query.order_by(Score.points.desc(), Score.timestamp).all()
    userNameScoreList = []
    for score in scores:
        userNameScoreList.append({'username': User.query.get(score.user_id).username,'score':score.points})

    return render_template('scoreboard.html', scores=userNameScoreList, organization=organization)


''' Machine Info '''

@ctf.route("/machine")
@login_required
def machine():
    user = User.query.get(current_user.id)
    if LOGGING:
        log = Logs.query.get(current_user.id)
        if log.visitedMachine is False:
            log.visitedMachine = True
            log.machineVisitTime = datetime.utcnow()
            db.session.commit()
    userHashForm = UserHashForm()
    rootHashForm = RootHashForm()
    return render_template('machine.html', userHashForm=userHashForm,
                           rootHashForm=rootHashForm, organization=organization, box=box)

''' Hash Submission Management '''

@ctf.route("/validateRootHash", methods=['POST'])
@login_required
def validateRootHash():
    userHashForm = UserHashForm()
    rootHashForm = RootHashForm()
    if rootHashForm.validate_on_submit():
        if rootHashForm.rootHash.data == rootHash:
            score = Score.query.get(current_user.id)
            if score.rootHash:
                flash("You already own System.", "success")
            else:
                score.rootHash = True
                score.points += rootScore
                score.timestamp = datetime.utcnow()
                if LOGGING:
                    log = Logs.query.get(current_user.id)
                    log.rootSubmissionIP = request.access_route[0]
                    log.rootSubmissionTime = datetime.utcnow()
                    log.rootOwnTime = str(log.rootSubmissionTime - log.machineVisitTime)
                db.session.commit()
                flash("Congrats! correct system hash.", "success")
        else:
            flash("Sorry! Wrong system hash", "danger")
        return render_template('machine.html', userHashForm=userHashForm,
                           rootHashForm=rootHashForm, organization=organization, box=box)
    else:
        return render_template('machine.html', userHashForm=userHashForm,
                           rootHashForm=rootHashForm, organization=organization, box=box)


@ctf.route("/validateUserHash", methods=['POST'])
@login_required
def validateUserHash():
    userHashForm = UserHashForm()
    rootHashForm = RootHashForm()
    if userHashForm.validate_on_submit():
        if userHashForm.userHash.data == userHash:
            score = Score.query.get(current_user.id)
            if score.userHash:
                flash("You already own User.", "success")
            else:
                score.userHash = True
                score.points += userScore
                score.timestamp = datetime.utcnow()
                if LOGGING:
                    log = Logs.query.get(current_user.id)
                    log.userSubmissionIP = request.access_route[0]
                    log.userSubmissionTime = datetime.utcnow()
                    log.userOwnTime = str(log.userSubmissionTime - log.machineVisitTime)
                db.session.commit()
                flash("Congrats! correct user hash.", "success")
        else:
            flash("Sorry! Wrong user hash", "danger")
        return render_template('machine.html', userHashForm=userHashForm,
                           rootHashForm=rootHashForm, organization=organization, box=box)
    else:
        return render_template('machine.html', userHashForm=userHashForm,
                           rootHashForm=rootHashForm, organization=organization, box=box)

src/FlaskRTBCTF/main/routes.py
from flask import render_template, Blueprint
from FlaskRTBCTF.config import organization, RunningTime
from FlaskRTBCTF.models import Notification

main = Blueprint('main', __name__)

''' Index page '''

@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', organization=organization, RunningTime=RunningTime)

@main.route("/notifications")
def notifications():
    notifs = Notification.query.order_by(Notification.timestamp.desc()).all()
    return render_template('notifications.html', organization=organization, title="Notifications", notifs=notifs)

src/FlaskRTBCTF/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from FlaskRTBCTF import db, bcrypt
from FlaskRTBCTF.config import organization, LOGGING
from FlaskRTBCTF.models import User, Score
if LOGGING:
    from FlaskRTBCTF.models import Logs
from FlaskRTBCTF.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from FlaskRTBCTF.users.utils import send_reset_email

from datetime import datetime

users = Blueprint('users', __name__)

''' User management '''

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash('Already Authenticated', 'info')
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        score = Score(user=user, userHash=False, rootHash=False, points=0)
        if LOGGING:
            log = Logs(user=user, accountCreationTime=datetime.utcnow(), visitedMachine=False, machineVisitTime=None, userSubmissionTime=None,
                       rootSubmissionTime=None, userSubmissionIP=None, rootSubmissionIP=None)
            db.session.add(log)
        db.session.add(user)
        db.session.add(score)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form, organization=organization)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash('Already Authenticated', 'info')
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data, force=True)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password.', 'danger')
    return render_template('login.html', title='Login', form=form, organization=organization)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged out.", "info")
    return redirect(url_for('main.home'))


@users.route("/account")
@login_required
def account():
    return render_template('account.html', title='Account', organization=organization)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form, organization=organization)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    user = User.verify_reset_token(token)
    
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    
    return render_template('reset_token.html', title='Reset Password', form=form, organization=organization)

src/FlaskRTBCTF/templates/account.html
{% extends "layout.html" %}


{% block content %}
 
    <div class="content-section">
        <h3>Username:</h3><span>{{ current_user.username }}</span>
        <hr/>
        <h3>Email: </h3>
        <span>{{ current_user.email }}</span>
    </div>

{% endblock content %}

src/FlaskRTBCTF/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
            <h1 class="display-5">Welcome to {{ organization['ctfname'] }}</h1>
            {% if current_user.is_authenticated %}
                <p class="lead">If you owned the box then you can submit the hashes <a class="red-underlined-link" href="{{ url_for('ctf.machine') }}">here</a>.</p>
            {% else %}
                <p class="lead">You need to <a class="red-underlined-link" href="{{ url_for('users.login') }}">login</a> first.</p>
            {% endif %}
      </div>
    </div>
</div>

<div class="content-section">
    <h2 class="title-heading">Rules</h2>
    <hr/>
    <ul>
        <li>Running time: <code>{{ RunningTime['from'].strftime("%Y-%m-%d %I:%M %p") }}</code> to <code>{{ RunningTime['to'].strftime("%Y-%m-%d %I:%M %p") }}</code> (All times in  <code>{{ RunningTime['TimeZone'] }}</code>)</li>
        <li>Needless to say: no bruteforcing (you'll never guess, anyway)</li>
        <li>Automated vulnerability scanners will get you nowhere(we know 'cause we made the box)</li>
        <li>Attacking this CTF infrastructure website is unnecessary. There are no hints.
            This website is for the sole purpose of registration, hash submission and management.</li>
        <li>We have tested the machine multiple, I repeat multiple times so if you are receiving a status code of 404 or 301. Figure it out yourself!</li>    
        <li>Have fun! :)</li>
    </ul>
</div>

{% endblock content %}

src/FlaskRTBCTF/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- "Metadata. The story behind the data" ~ Elliot Alderson -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Favicon -->
  	<link rel='shortcut icon' type='image/x-icon' href="{{ url_for('static', filename='favicon.ico')}}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <!-- local css -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <!-- Title --> 
    {% if title %}
        <title>{{ organization['ctfname'] }} - {{ title }}</title>
    {% else %}
        <title>{{ organization['ctfname'] }}</title>
    {% endif %}
</head>
<body>

    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">{{ organization['ctfname'] }}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.notifications') }}">Notifications</a>
              <a class="nav-item nav-link" href="{{ url_for('ctf.scoreboard') }}">Scoreboard</a>
              <a class="nav-item nav-link" href="{{ url_for('ctf.machine') }}">Machine</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  {% if current_user.isAdmin %}
                    <a class="nav-item nav-link" href="/admin">Admin Controls</a>
                  {% endif %}
                  <a class="nav-item nav-link" href="{{ url_for('users.account') }}">@{{ current_user.username }}</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                
                <div class="alert alert-{{ category }}">
                    {% if category == "danger" %}
                      <i class="fas fa-exclamation-triangle"></i>
                    {% elif category == "success" %}
                      <i class="far fa-check-circle"></i>
                    {% else %}
                      <i class="fas fa-info-circle"></i>
                    {% endif %}
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
              <h3>{{ organization['name'] }}</h3>
              <p class='text-muted'>{{ organization['tagline'] }}
                <ul class="list-group">
                  <a target="_blank" href="{{ organization['website']['url'] }}" class="list-group-item list-group-item-action">{{ organization['website']['name'] }}</a>
                  <a target="_blank" href="{{ organization['website_2']['url'] }}" class="list-group-item list-group-item-action">{{ organization['website_2']['name'] }}</a>
                  <a target="_blank" href="{{ organization['website_3']['url'] }}" class="list-group-item list-group-item-action">{{ organization['website_3']['name'] }}</a>
                </ul>
              </p>
            </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

src/FlaskRTBCTF/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}
                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="custom-control custom-checkbox">
                    {{ form.remember(class="custom-control-input") }}
                    {{ form.remember.label(class="custom-control-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-dark btn-hover-red") }}
            </div>
            <small>
                <a href="{{ url_for('users.reset_request') }}" class="red-underlined-link">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-light">
            Need An Account? <a class="ml-2 red-underlined-link" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
    
{% endblock content %}

src/FlaskRTBCTF/templates/machine.html
{% extends "layout.html" %}

{% block content %}

<div class="content-section">

    <!-- Machine Info -->

    <div class="machine-heading">{{ box['name'] }}</div>
    <hr/>
    <div class="row">
    <div class="col-sm-6">
        <div class="card">
          <div class="card-header">IP</div>  
          <h5 class="card-title">{{ box['ip'] }}</h5>
          <!--
          <div class="card-body">
          <p class="card-text">WIFI: </p>
        </div>
          -->

        </div>
    </div>
    <div class="col-sm-6">
        <div class="card">
          <div class="card-header">OS</div>   
          <h5 class="card-title">{{ box['os'] }}</h5>
        </div>
    </div>
    </div>
    <div class="row">
    <div class="col-sm-6">
        <div class="card">
          <div class="card-header">Points</div> 
            <h5 class="card-title">User: {{ box['points']['user'] }} | Root: {{ box['points']['root'] }}</h5>
        </div>
    </div> 
    <div class="col-sm-6">
        <div class="card">
          <div class="card-header">Difficulty Level</div>   
          <h5 class="card-title">{{ box['hardness'] }}</h5>
        </div>
    </div>       
    </div>

    <hr/>

    <!-- User Hash Form -->
    <form class="form-inline" method="POST" action="{{ url_for('ctf.validateUserHash') }}">
        {{ userHashForm.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ userHashForm.userHash.label(class="form-control-label") }}
                {% if userHashForm.userHash.errors %}
                    {{ userHashForm.userHash(class="form-control form-control-sm ml-4 mr-4 is-invalid", autocomplete="off") }}
                    <div class="invalid-feedback">
                        {% for error in userHashForm.userHash.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                        {{ userHashForm.userHash(class="form-control form-control-sm ml-4 mr-4", autocomplete="off") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ userHashForm.submit(class="btn btn-dark btn-hover-red") }}
        </div>
    </form>
    <hr/>
    <!-- System Hash Form-->
    <form class="form-inline" method="POST" action="{{ url_for('ctf.validateRootHash') }}">
        {{ rootHashForm.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ rootHashForm.rootHash.label(class="form-control-label") }}
                {% if rootHashForm.rootHash.errors %}
                    {{ rootHashForm.rootHash(class="form-control form-control-sm ml-4 mr-4 is-invalid", autocomplete="off") }}
                    <div class="invalid-feedback">
                        {% for error in rootHashForm.rootHash.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ rootHashForm.rootHash(class="form-control form-control-sm ml-4 mr-4", autocomplete="off") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ rootHashForm.submit(class="btn btn-dark btn-hover-red") }}
        </div>
    </form>

    
</div>

{% endblock content %}

src/FlaskRTBCTF/templates/notifications.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    {% for notif in notifs %}
        <div class="content-section">
            <h3 class="title-heading">{{ notif['title'] }}</h3>
            <div class="float-right">
            <small>Notification #{{ notif['id'] }} - posted at <code>{{ notif['timestamp'].strftime("%Y-%m-%d %I:%M %p") }} UTC</code></small>
            </div><br/>
            <hr/>
            <p>{{ notif['body'] }}</p>
        </div>
    {% endfor %}
</div>

{% endblock content %}

src/FlaskRTBCTF/templates/register.html
{% extends "layout.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-dark btn-hover-red") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-light">
            Already Have An Account? <a class="ml-2 red-underlined-link" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
    
{% endblock content %}

src/FlaskRTBCTF/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-dark btn-hover-red") }}
            </div>
        </form>
    </div>

{% endblock content %}

src/FlaskRTBCTF/templates/reset_token.html
{% extends "layout.html" %}

{% block content %}

    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid", autocomplete="off") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control", autocomplete="off") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-dark btn-hover-red") }}
            </div>
        </form>
    </div>

{% endblock content %}

src/FlaskRTBCTF/templates/scoreboard.html
{% extends "layout.html" %}
{% block content %}

    <div class="content-section">
    {% if scores %}
        <h2 class="title-heading">Scoreboard</h2>
        <div class="table-responsive">
            <table class="table custom-table table-borderless">
                <thead>
                <tr class="table-row-even">
                    <th scope="col">Rank</th>
                    <th scope="col">Username</th>
                    <th scope="col">Score</th>
                </tr>
                </thead>
                <tbody>
                {% for score in scores %}
                    {% if loop.index%2 != 0 %}
                        <tr class="table-row-odd">
                            <th scope="row">{{ loop.index }}</th>
                            <td>{{ score['username'] }}</td>
                            <td>{{ score['score'] }}</td>
                        </tr>
                    {% else %}
                        <tr class="table-row-odd">
                            <th scope="row">{{ loop.index }}</th>
                            <td>{{ score['username'] }}</td>
                            <td>{{ score['score'] }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
    </div>

{% endblock content %}